In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from certifi import where

In [23]:
df = pd.read_csv('../data/raw/AMAT_IMPUTED_NUMERIC_3117ind_15456snp_0.05MAF_0.70coverage_0.10het.csv')

#Convert index to a column
df = df.reset_index()

df = df.rename(columns={'index':'Genotype'})
print("Dataset shape:", df.shape)
df.head()

C:\Users\top\AppData\Local\Temp\ipykernel_20212\184532916.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df = df.reset_index()

Dataset shape: (3117, 15457)

,Genotype,S1A_687822,S1A_1195489,S1A_1234081,S1A_4781815,S1A_4929734,S1A_5190325,S1A_5548635,S1A_5548650,S1A_5857413,...,SUNKNOWN_323958,SUNKNOWN_336365,SUNKNOWN_336436,SUNKNOWN_336436.1,SUNKNOWN_339127,SUNKNOWN_343096,SUNKNOWN_349202,SUNKNOWN_349202.1,SUNKNOWN_349202.2,SUNKNOWN_349202.3
0,0566A1_3_1_47,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0
1,0762A1_2_8,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,0,1.0,1.0,1.0,1.0
2,13VTK59_55,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,-1.0,1,1.0,1.0,1.0,1.0
3,20PU_0001,1,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,0.0,1.0,0.0
4,21PU_0015,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,-1,1.0,0.0,0.0,1.0

In [24]:
df

,Genotype,S1A_687822,S1A_1195489,S1A_1234081,S1A_4781815,S1A_4929734,S1A_5190325,S1A_5548635,S1A_5548650,S1A_5857413,...,SUNKNOWN_323958,SUNKNOWN_336365,SUNKNOWN_336436,SUNKNOWN_336436.1,SUNKNOWN_339127,SUNKNOWN_343096,SUNKNOWN_349202,SUNKNOWN_349202.1,SUNKNOWN_349202.2,SUNKNOWN_349202.3
0,0566A1_3_1_47,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0
1,0762A1_2_8,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,0,1.0,1.0,1.0,1.0
2,13VTK59_55,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,-1.0,1,1.0,1.0,1.0,1.0
3,20PU_0001,1,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,0.0,1.0,0.0
4,21PU_0015,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,-1,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3112,X16_1081_22_11_3_13,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0
3113,X16_1088_99_14_1_4,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,-1,1.0,1.0,-1.0,1.0,1,-1.0,1.0,1.0,1.0
3114,X16_1092_7_6_5_1,0,1.0,1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,...,1,1.0,1.0,-1.0,1.0,1,1.0,1.0,1.0,1.0
3115,X16_3013_1_12_5,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,-1.0,1.0,1,0.0,1.0,1.0,1.0
3116,Zenda,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0

In [25]:
print(df.columns[-5:])

Index(['SUNKNOWN_343096', 'SUNKNOWN_349202', 'SUNKNOWN_349202.1',
       'SUNKNOWN_349202.2', 'SUNKNOWN_349202.3'],
      dtype='str')

In [29]:
df_target = pd.read_csv("../data/raw/2021-2022_Across_Years_Phenomic_Data_VIS-NIR.csv"
                        )
df_target = df_target[['Genotype','DON']]
print("Dataset shape:", df_target.shape)
df_target.head()

Dataset shape: (558, 2)

        Genotype        DON
0  0566A1_3_1_47  13.126081
1     0762A1_2_8  16.491306
2     13VTK59_55  16.126081
3     Ambassador  53.085216
4        Catawba  15.257973

In [30]:
merge_df = pd.merge(df, df_target, left_on="Genotype", right_on="Genotype",how='inner')

In [31]:
merge_df

,Genotype,S1A_687822,S1A_1195489,S1A_1234081,S1A_4781815,S1A_4929734,S1A_5190325,S1A_5548635,S1A_5548650,S1A_5857413,...,SUNKNOWN_336365,SUNKNOWN_336436,SUNKNOWN_336436.1,SUNKNOWN_339127,SUNKNOWN_343096,SUNKNOWN_349202,SUNKNOWN_349202.1,SUNKNOWN_349202.2,SUNKNOWN_349202.3,DON
0,0566A1_3_1_47,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,13.126081
1,0762A1_2_8,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0,1.0,1.0,1.0,1.0,16.491306
2,13VTK59_55,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,-1.0,1,1.0,1.0,1.0,1.0,16.126081
3,Ambassador,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,53.085216
4,CN18_20_2,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,50.526081
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
544,VA17W_75,1,1.0,-1.0,-1.0,1.0,-1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,-1.0,1,1.0,1.0,1.0,0.0,14.926081
545,X08C_1077_11_18_3,1,1.0,1.0,1.0,-1.0,1.0,1.0,0.0,1.0,...,0.0,1.0,0.0,1.0,-1,0.0,1.0,-1.0,1.0,22.824640
546,X08_1181_61_15_5,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,18.426081
547,X11_0420_120_13_3,1,-1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,-1.0,1.0,1,1.0,1.0,1.0,1.0,19.626081
548,X12_924_40_7_5,1,1.0,1.0,1.0,-1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,-1.0,1.0,1,0.0,1.0,0.0,1.0,13.726081

In [36]:
merge_df.isna().sum()
np.where(merge_df.isna())

(array([], dtype=int64), array([], dtype=int64))

In [32]:
merge_df.to_csv('../data/processed/final_genomics_train_data.csv', index=False)
print("Dataset saved successfully!")

Dataset saved successfully!

In [39]:
df_test = pd.read_csv('../data/processed/final_genomics_train_data.csv')

In [41]:
print(f'Dataset shape: {df_test.shape}')
df_test.head()

Dataset shape: (549, 15458)

,Genotype,S1A_687822,S1A_1195489,S1A_1234081,S1A_4781815,S1A_4929734,S1A_5190325,S1A_5548635,S1A_5548650,S1A_5857413,...,SUNKNOWN_336365,SUNKNOWN_336436,SUNKNOWN_336436.1,SUNKNOWN_339127,SUNKNOWN_343096,SUNKNOWN_349202,SUNKNOWN_349202.1,SUNKNOWN_349202.2,SUNKNOWN_349202.3,DON
0,0566A1_3_1_47,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,13.126081
1,0762A1_2_8,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,0,1.0,1.0,1.0,1.0,16.491306
2,13VTK59_55,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,-1.0,1,1.0,1.0,1.0,1.0,16.126081
3,Ambassador,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,53.085216
4,CN18_20_2,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1,1.0,1.0,1.0,1.0,50.526081